# Generated by Django 4.0.4 on 2022-05-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipovehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=30)),
                ('marcaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.marca')),
                ('tipovehiculoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.tipovehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='marca',
            field=models.ManyToManyField(through='vehiculo.Vehiculo', to='marca.marca'),
        ),
    ]
